sudo: required

language: node_js

node_js:
 - '4.4.5'

before_install:
 - curl https://install.meteor.com/ | sh

services:
 - mongodb

script:
 - meteor update
 - meteor --settings settings.json
 - exit
